### ISSUE TITLE
SHA256 Signed Authentication Requests Fail with "Invalid Key Type"

### ISSUE THREAD

**Issue by jastorino82** [simplesamlphp/xmlsec#3]
I have simplesamlphp configured as an IDP.  When receiving a SAML authentication request from an SP that is signed with SHA256, I get "Invalid Key Type" from simplesamlphp.  

Looking at the authentication request, I can see that the SP is sending "SigAlg=http://www.w3.org/2001/04/xmlenc#sha256"

Looking at the source code, it seems that is not a supported type.  I'm not a SAML expert, but I'm trying to understand why a seemingly common digest wouldn't be supported.  I do see in the source support for xmldsig/rsa-sha256 but I'm not sure if that is the same thing.  Not sure if this is a problem with the SP not sending the correct string here, or possibly a bug in the IDP code.

**Comment by jaimeperez** [comment]
Hi @jastorino82,

Both SimpleSAMLphp and xmlseclibs (note that this is a fork of the original library used in SimpleSAML) support RSA-SHA256 for digital signatures. However, `http://www.w3.org/2001/04/xmlenc#sha256` is not a valid signature algorithm identifier. The right one to use would be `http://www.w3.org/2000/09/xmldsig#rsa-sha256`. Note that the one you are receiving is the identifier of the SHA256 digest method for its use in encryption, not a digital signature algorithm.
